config/routes.rb
Rails.application.routes.draw do
  resources :quartets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quartet.rb
class Quartet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quartets_controller.rb
class QuartetsController < ApplicationController
  before_action :set_quartet, only: [:show, :edit, :update, :destroy]

  # GET /quartets
  # GET /quartets.json
  def index
    @quartets = Quartet.all
  end

  # GET /quartets/1
  # GET /quartets/1.json
  def show
  end

  # GET /quartets/new
  def new
    @quartet = Quartet.new
  end

  # GET /quartets/1/edit
  def edit
  end

  # POST /quartets
  # POST /quartets.json
  def create
    @quartet = Quartet.new(quartet_params)

    respond_to do |format|
      if @quartet.save
        format.html { redirect_to @quartet, notice: 'Quartet was successfully created.' }
        format.json { render :show, status: :created, location: @quartet }
      else
        format.html { render :new }
        format.json { render json: @quartet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quartets/1
  # PATCH/PUT /quartets/1.json
  def update
    respond_to do |format|
      if @quartet.update(quartet_params)
        format.html { redirect_to @quartet, notice: 'Quartet was successfully updated.' }
        format.json { render :show, status: :ok, location: @quartet }
      else
        format.html { render :edit }
        format.json { render json: @quartet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quartets/1
  # DELETE /quartets/1.json
  def destroy
    @quartet.destroy
    respond_to do |format|
      format.html { redirect_to quartets_url, notice: 'Quartet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quartet
      @quartet = Quartet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quartet_params
      params.require(:quartet).permit(:country, :uri, :image, :year, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quartets_helper.rb
module QuartetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quatuor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quartets/_form.html.erb
<%= form_with(model: quartet, local: true) do |form| %>
  <% if quartet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quartet.errors.count, "error") %> prohibited this quartet from being saved:</h2>

      <ul>
      <% quartet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :uri %>
    <%= form.text_field :uri %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quartets/edit.html.erb
<h1>Editing Quartet</h1>

<%= render 'form', quartet: @quartet %>

<%= link_to 'Show', @quartet %> |
<%= link_to 'Back', quartets_path %>

app/views/quartets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quartets</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>Uri</th>
      <th>Image</th>
      <th>Year</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quartets.each do |quartet| %>
      <tr>
        <td><%= quartet.country %></td>
        <td><%= quartet.uri %></td>
        <td><%= quartet.image %></td>
        <td><%= quartet.year %></td>
        <td><%= quartet.title %></td>
        <td><%= link_to 'Show', quartet %></td>
        <td><%= link_to 'Edit', edit_quartet_path(quartet) %></td>
        <td><%= link_to 'Destroy', quartet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quartet', new_quartet_path %>

app/views/quartets/new.html.erb
<h1>New Quartet</h1>

<%= render 'form', quartet: @quartet %>

<%= link_to 'Back', quartets_path %>

app/views/quartets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @quartet.country %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @quartet.uri %>
</p>

<p>
  <strong>Image:</strong>
  <%= @quartet.image %>
</p>

<p>
  <strong>Year:</strong>
  <%= @quartet.year %>
</p>

<p>
  <strong>Title:</strong>
  <%= @quartet.title %>
</p>

<%= link_to 'Edit', edit_quartet_path(@quartet) %> |
<%= link_to 'Back', quartets_path %>